{
 "title": "op-interop-mon",
 "description": "add version",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(op_interop_mon_default_executing_block_range,chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(op_interop_mon_default_message_status)",
     "legendFormat": "total jobs"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_interop_mon_default_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Ranges",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "repeat": "chain",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_interop_mon_default_executing_block_range{range_type=\"max\", chain_id=\"$chain\"}",
     "legendFormat": "{{chain_id}}-exec-max"
    },
    {
     "expr": "op_interop_mon_default_executing_block_range{range_type=\"min\", chain_id=\"$chain\"}",
     "legendFormat": "{{chain_id}}-exec-min"
    },
    {
     "expr": "op_interop_mon_default_initiating_block_range{range_type=\"max\", chain_id=\"$chain\"}",
     "legendFormat": "{{chain_id}}-init-max"
    },
    {
     "expr": "op_interop_mon_default_initiating_block_range{range_type=\"min\", chain_id=\"$chain\"}",
     "legendFormat": "{{chain_id}}-init-min"
    }
   ]
  },
  {
   "title": "Executing Message Status by ChainID",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "op_interop_mon_default_message_status{namespace=\"op-interop-mon\"}",
     "legendFormat": "{{initiating_chain_id}}->{{executing_chain_id}}-{{status}}"
    }
   ]
  }
 ]
}